# Generated by Django 6.0.5 on 2026-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(default='192.168.1.100')),
                ('packet_size', models.IntegerField()),
                ('request_rate', models.IntegerField()),
                ('failed_logins', models.IntegerField()),
                ('attack_type', models.CharField(default='Unknown', max_length=50)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('action_taken', models.CharField(default='Monitored Only', max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
